apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: nifi
spec:
  serviceName: nifi
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      volumes:
        - name: nifi-conf
          emptyDir: {}

      initContainers:
        - name: init-nifi-conf
          image: ${FULL_TAG}
          command:
            - sh
            - -c
            - |
              cp /opt/nifi/conf/nifi.properties /config/nifi.properties
              sed -i \
                -e 's@^#\?nifi.web.http.host=.*@nifi.web.http.host=0.0.0.0@' \
                -e 's@^#\?nifi.web.http.port=.*@nifi.web.http.port=8080@' \
                -e 's@^#\?nifi.web.http.network.interface.default=.*@nifi.web.http.network.interface.default=@' \
                -e 's@^nifi.web.https.host=.*@# &@' \
                -e 's@^nifi.web.https.port=.*@# &@' \
                -e 's@^nifi.security\..*@# &@' \
                -e 's@^#\?nifi.remote.input.host=.*@nifi.remote.input.host=@' \
                -e 's@^#\?nifi.remote.input.secure=.*@nifi.remote.input.secure=false@' \
                -e 's@^#\?nifi.remote.input.socket.port=.*@nifi.remote.input.socket.port=@' \
                -e 's@^#\?nifi.remote.input.http.enabled=.*@nifi.remote.input.http.enabled=true@' \
                -e 's@^#\?nifi.remote.input.http.transaction.ttl=.*@nifi.remote.input.http.transaction.ttl=30 sec@' \
                -e 's@^#\?nifi.remote.contents.cache.expiration=.*@nifi.remote.contents.cache.expiration=30 secs@' \
                /config/nifi.properties
          volumeMounts:
            - name: nifi-conf
              mountPath: /config

      containers:
        - name: nifi
          image: ${FULL_TAG}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: nifi-conf
              mountPath: /opt/nifi/conf/nifi.properties
              subPath: nifi.properties
            - name: data
              mountPath: /opt/nifi/data

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: gp2-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
