apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-properties
  namespace: nifi
data:
  nifi.properties: |
    nifi.web.http.host=0.0.0.0
    nifi.web.http.port=8080
    nifi.web.http.network.interface.default=
    #nifi.web.https.host=
    #nifi.web.https.port=
    #nifi.security.*
    nifi.remote.input.host=
    nifi.remote.input.secure=false
    nifi.remote.input.socket.port=
    nifi.remote.input.http.enabled=true
    nifi.remote.input.http.transaction.ttl=30 sec
    nifi.remote.contents.cache.expiration=30 secs
