apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: nifi
spec:
  serviceName: nifi
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          image: ${FULL_TAG}          
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NIFI_WEB_HTTP_HOST
              value: "0.0.0.0"
            - name: NIFI_WEB_HTTP_PORT
              value: "8080"
            - name: NIFI_WEB_HTTP_NETWORK_INTERFACE_DEFAULT
              value: ""
            - name: NIFI_REMOTE_INPUT_HOST
              value: ""
            - name: NIFI_REMOTE_INPUT_SECURE
              value: "false"
            - name: NIFI_REMOTE_INPUT_SOCKET_PORT
              value: ""
            - name: NIFI_REMOTE_INPUT_HTTP_ENABLED
              value: "true"
            - name: NIFI_REMOTE_INPUT_HTTP_TRANSACTION_TTL
              value: "30 sec"
            - name: NIFI_REMOTE_CONTENTS_CACHE_EXPIRATION
              value: "30 secs"
          volumeMounts:
            - name: data
              mountPath: /opt/nifi/data     
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: gp2-csi
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi