---
- name: Full NiFi Deployment
  hosts: ec2
  remote_user: ubuntu
  become: yes
  vars:
    nifi_home: /opt/nifi-1.26.0
    nifi_user: ubuntu
    nifi_group: ubuntu
    nifi_artifact_url: https://archive.apache.org/dist/nifi/1.26.0/nifi-1.26.0-bin.zip
    nifi_zip: nifi-1.26.0-bin.zip
    remote_zip_path: /home/ubuntu/nifi-1.26.0-bin.zip
  tasks:
    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present
        update_cache: yes
    - name: Download NiFi artifact
      get_url:
        url: "{{ nifi_artifact_url }}"
        dest: "{{ remote_zip_path }}"
        mode: "0644"
    - name: Unarchive NiFi to {{ nifi_home }}
      unarchive:
        src: "{{ remote_zip_path }}"
        dest: /opt
        remote_src: yes
        owner: "{{ nifi_user }}"
        group: "{{ nifi_group }}"
    - name: Set ownership on NiFi directory
      file:
        path: "{{ nifi_home }}"
        recurse: yes
        owner: "{{ nifi_user }}"
        group: "{{ nifi_group }}"
    - name: Ensure NiFi scripts are executable
      file:
        path: "{{ nifi_home }}/bin/nifi.sh"
        mode: "0755"
    - name: Ensure NiFi logs directory exists
      file:
        path: "{{ nifi_home }}/logs"
        state: directory
        owner: "{{ nifi_user }}"
        group: "{{ nifi_group }}"
        mode: "0755"
    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
    - name: Find JAVA_HOME
      shell: readlink -f $(which java) | sed "s:bin/java::"
      register: java_home_path
      changed_when: false
    - name: Configure java.home in bootstrap.conf
      lineinfile:
        path: "{{ nifi_home }}/conf/bootstrap.conf"
        regexp: ^java\.home=
        line: java.home={{ java_home_path.stdout }}
        create: yes
    - name: Ensure NiFi HTTP host is 0.0.0.0
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: ^#?nifi\.web\.http\.host=
        line: nifi.web.http.host=0.0.0.0
      notify: Restart NiFi
    - name: Ensure NiFi HTTP port is 8080
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: ^#?nifi\.web\.http\.port=
        line: nifi.web.http.port=8080
        create: yes
    - name: Ensure HTTP network interface default is blank
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: ^#?nifi\.web\.http\.network\.interface\.default=
        line: nifi.web.http.network.interface.default=
        create: yes
    - name: Comment out NiFi HTTPS & security props
      replace:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: ^(nifi\.web\.https\.(host|port)|nifi\.security\.(keystore|keystoreType|keystorePasswd|keyPasswd|truststore|truststoreType|truststorePasswd))=.*
        replace: "# \\\\0"
    - name: Clear remote input host
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: ^#?nifi\.remote\.input\.host=
        line: nifi.remote.input.host=
        create: yes
    - name: Disable secure Site-to-Site
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: ^#?nifi\.remote\.input\.secure=
        line: nifi.remote.input.secure=false
        create: yes
    - name: Clear remote input socket port
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: ^#?nifi\.remote\.input\.socket\.port=
        line: nifi.remote.input.socket.port=
        create: yes
    - name: Enable Site-to-Site over HTTP
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: ^#?nifi\.remote\.input\.http\.enabled=
        line: nifi.remote.input.http.enabled=true
        create: yes
    - name: Set Site-to-Site HTTP transaction TTL
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: ^#?nifi\.remote\.input\.http\.transaction\.ttl=
        line: nifi.remote.input.http.transaction.ttl=30 sec
        create: yes
    - name: Set content cache expiration
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: ^#?nifi\.remote\.contents\.cache\.expiration=
        line: nifi.remote.contents.cache.expiration=30 secs
        create: yes
    - name: Start NiFi
      become_user: "{{ nifi_user }}"
      shell: "{{ nifi_home }}/bin/nifi.sh start"
      environment:
        JAVA_HOME: "{{ java_home_path.stdout }}"
    - name: Wait for NiFi to start on port 8080 (local)
      wait_for:
        host: 127.0.0.1
        port: 8080
        delay: 10
        timeout: 300
      delegate_to: "{{ inventory_hostname }}"
    - name: Check NiFi status
      shell: "{{ nifi_home }}/bin/nifi.sh status"
      register: nifi_status
    - name: Print NiFi status
      debug:
        var: nifi_status.stdout
  handlers:
    - name: Restart NiFi
      become_user: "{{ nifi_user }}"
      shell: "{{ nifi_home }}/bin/nifi.sh restart"
