---
- name: Deploy and configure NiFi
  hosts: ec2
  become: yes
  tasks:
    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Unarchive NiFi to /opt
      unarchive:
        src: /home/ubuntu/nifi-1.26.0-bin.zip
        dest: /opt
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set ownership on NiFi directory
      file:
        path: /opt
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Set JAVA_HOME in bootstrap.conf
      lineinfile:
        path: /opt/nifi-1.26.0/conf/bootstrap.conf
        regexp: '^JAVA_HOME='
        line: 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
        create: yes

    - name: Set nifi.web.http.port=8080 in nifi.properties
      lineinfile:
        path: /opt/nifi-1.26.0/conf/nifi.properties
        regexp: '^nifi.web.http.port='
        line: 'nifi.web.http.port=8080'
        create: yes

    - name: Comment out nifi.web.https.port in nifi.properties
      replace:
        path: /opt/nifi-1.26.0/conf/nifi.properties
        regexp: '^(nifi.web.https.port=.*)'
        replace: '# \1'

    - name: Comment out nifi.web.https.host in nifi.properties
      replace:
        path: /opt/nifi-1.26.0/conf/nifi.properties
        regexp: '^(nifi.web.https.host=.*)'
        replace: '# \1'

    - name: Start NiFi
      command: /opt/nifi-1.26.0/bin/nifi.sh start

    - name: Wait for NiFi to start
      wait_for:
        port: 8080
        delay: 10
        timeout: 60
