---
- name: Install Java 17
  hosts: ec2
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Find JAVA_HOME
      shell: readlink -f $(which java) | sed "s:bin/java::"
      register: java_home_path
      changed_when: false

    - name: Set JAVA_HOME for all sessions (profile)
      lineinfile:
        path: /etc/profile.d/java.sh
        create: yes
        mode: "0755"
        line: export JAVA_HOME={{ java_home_path.stdout }}

    - name: Export JAVA_HOME for current playbook run
      set_fact:
        ansible_env:
          JAVA_HOME: "{{ java_home_path.stdout }}"
