---
- name: Install Java 17
  hosts: nifi
  become: yes
  gather_facts: no

  tasks:
    - name: Install OpenJDK 17
      apt:
        update_cache: yes
        name: openjdk-17-jdk
        state: present
