---
- name: Deploy & Start Apache NiFi
  hosts: ec2
  become: yes
  vars:
    nifi_version: "1.26.0"
    nifi_zip_url: "https://archive.apache.org/dist/nifi/{{ nifi_version }}/nifi-{{ nifi_version }}-bin.zip"
    nifi_zip_dest: "/home/ubuntu/nifi-{{ nifi_version }}-bin.zip"
    nifi_install_dir: "/opt/nifi-{{ nifi_version }}"
  tasks:
    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Download NiFi {{ nifi_version }} via wget
      shell: |
        wget --progress=dot:giga \
             -O {{ nifi_zip_dest }} \
             {{ nifi_zip_url }}
      args:
        creates: "{{ nifi_zip_dest }}"

    - name: Unarchive NiFi to /opt
      unarchive:
        src: "{{ nifi_zip_dest }}"
        dest: /opt/
        remote_src: true
        creates: "{{ nifi_install_dir }}"

    - name: Set ownership on NiFi directory
      file:
        path: "{{ nifi_install_dir }}"
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Configure NiFi HTTP host to listen on all interfaces
      lineinfile:
        path: "{{ nifi_install_dir }}/conf/nifi.properties"
        regexp: '^nifi.web.http.host='
        line: 'nifi.web.http.host=0.0.0.0'

    - name: Start NiFi service
      shell: "{{ nifi_install_dir }}/bin/nifi.sh start"
      args:
        creates: "{{ nifi_install_dir }}/work/nar"

    - name: Verify NiFi is running
      shell: "{{ nifi_install_dir }}/bin/nifi.sh status"
      register: nifi_status
      changed_when: false

    - name: Show NiFi status
      debug:
        var: nifi_status.stdout_lines