---
- name: Install Java 17
  hosts: ec2
  become: yes
  tasks:
    - name: Update APT cache
      apt: { update_cache: yes }
    - name: Install OpenJDK 17
      apt: { name: openjdk-17-jdk, state: present }
                                                      